"""initial schema

Revision ID: 0e411c078c0a
Revises:
Create Date: 2026-03-19 21:35:14.299600

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e411c078c0a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("digest_date", sa.Date(), nullable=True),
        sa.Column("trigger_source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("digest_date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("topic_label", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("perspectives", sa.Text(), nullable=True),
        sa.Column("ai_comment", sa.Text(), nullable=True),
        sa.Column("heat_score", sa.Float(), nullable=False),
        sa.Column("ai_importance_score", sa.Float(), nullable=False),
        sa.Column("merge_reason", sa.Text(), nullable=True),
        sa.Column("tweet_count", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "twitter_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("twitter_handle", sa.String(length=100), nullable=False),
        sa.Column("twitter_user_id", sa.String(length=50), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.String(length=1000), nullable=True),
        sa.Column("followers_count", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_fetch_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("twitter_handle"),
    )
    op.create_table(
        "api_cost_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_date", sa.Date(), nullable=False),
        sa.Column("service", sa.String(length=20), nullable=False),
        sa.Column("call_type", sa.String(length=50), nullable=False),
        sa.Column("endpoint", sa.String(length=200), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("job_run_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_run_id"],
            ["job_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_digest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("digest_date", sa.Date(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content_markdown", sa.Text(), nullable=True),
        sa.Column("content_html", sa.Text(), nullable=True),
        sa.Column("cover_image_path", sa.String(length=500), nullable=True),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("publish_mode", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("job_run_id", sa.Integer(), nullable=True),
        sa.Column("preview_token", sa.String(length=100), nullable=True),
        sa.Column("preview_expires_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_run_id"],
            ["job_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fetch_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fetch_date", sa.Date(), nullable=False),
        sa.Column("job_run_id", sa.Integer(), nullable=True),
        sa.Column("total_accounts", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.Column("new_tweets", sa.Integer(), nullable=False),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_run_id"],
            ["job_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tweet_id", sa.String(length=50), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("digest_date", sa.Date(), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("media_urls", sa.Text(), nullable=True),
        sa.Column("translated_text", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("ai_comment", sa.Text(), nullable=True),
        sa.Column("base_heat_score", sa.Float(), nullable=False),
        sa.Column("ai_importance_score", sa.Float(), nullable=False),
        sa.Column("heat_score", sa.Float(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("retweets", sa.Integer(), nullable=False),
        sa.Column("replies", sa.Integer(), nullable=False),
        sa.Column("tweet_url", sa.String(length=500), nullable=True),
        sa.Column("tweet_time", sa.DateTime(), nullable=False),
        sa.Column("quoted_text", sa.Text(), nullable=True),
        sa.Column("is_quote_tweet", sa.Boolean(), nullable=False),
        sa.Column("is_self_thread_reply", sa.Boolean(), nullable=False),
        sa.Column("is_ai_relevant", sa.Boolean(), nullable=False),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["twitter_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tweet_id"),
    )
    op.create_index(op.f("ix_tweets_digest_date"), "tweets", ["digest_date"], unique=False)
    op.create_index(op.f("ix_tweets_heat_score"), "tweets", ["heat_score"], unique=False)
    op.create_index(op.f("ix_tweets_is_processed"), "tweets", ["is_processed"], unique=False)
    op.create_index(op.f("ix_tweets_topic_id"), "tweets", ["topic_id"], unique=False)
    op.create_table(
        "digest_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("digest_id", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("item_ref_id", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_excluded", sa.Boolean(), nullable=False),
        sa.Column("snapshot_title", sa.String(length=200), nullable=True),
        sa.Column("snapshot_summary", sa.Text(), nullable=True),
        sa.Column("snapshot_translation", sa.Text(), nullable=True),
        sa.Column("snapshot_comment", sa.Text(), nullable=True),
        sa.Column("snapshot_perspectives", sa.Text(), nullable=True),
        sa.Column("snapshot_heat_score", sa.Float(), nullable=False),
        sa.Column("snapshot_author_name", sa.String(length=200), nullable=True),
        sa.Column("snapshot_author_handle", sa.String(length=100), nullable=True),
        sa.Column("snapshot_tweet_url", sa.String(length=500), nullable=True),
        sa.Column("snapshot_source_tweets", sa.Text(), nullable=True),
        sa.Column("snapshot_topic_type", sa.String(length=20), nullable=True),
        sa.Column("snapshot_tweet_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["digest_id"],
            ["daily_digest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest_id", "item_type", "item_ref_id", name="uq_digest_item_ref"),
    )
    # ### end Alembic commands ###

    # system_config 种子数据
    system_config = sa.table(
        "system_config",
        sa.column("key", sa.String),
        sa.column("value", sa.Text),
        sa.column("description", sa.String),
    )
    op.bulk_insert(
        system_config,
        [
            {"key": "push_time", "value": "08:00", "description": "推送参考时间"},
            {"key": "push_days", "value": "1,2,3,4,5,6,7", "description": "推送日（1=周一）"},
            {"key": "top_n", "value": "10", "description": "每日推送条数上限"},
            {"key": "min_articles", "value": "1", "description": "低于此值显示警告"},
            {"key": "display_mode", "value": "simple", "description": "展示模式（预留）"},
            {"key": "publish_mode", "value": "manual", "description": "发布模式"},
            {"key": "enable_cover_generation", "value": "false", "description": "封面图生成开关"},
            {"key": "cover_generation_timeout", "value": "30", "description": "封面图超时（秒）"},
            {"key": "notification_webhook_url", "value": "", "description": "通知 Webhook URL"},
            {"key": "admin_password_hash", "value": "", "description": "管理员密码哈希"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("digest_items")
    op.drop_index(op.f("ix_tweets_topic_id"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_is_processed"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_heat_score"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_digest_date"), table_name="tweets")
    op.drop_table("tweets")
    op.drop_table("fetch_log")
    op.drop_table("daily_digest")
    op.drop_table("api_cost_log")
    op.drop_table("twitter_accounts")
    op.drop_table("topics")
    op.drop_table("system_config")
    op.drop_table("job_runs")
    # ### end Alembic commands ###
