"""add topic digest_date index

Revision ID: 337e9caa2833
Revises: 0e411c078c0a
Create Date: 2026-03-22 12:04:28.744847

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "337e9caa2833"
down_revision: str | Sequence[str] | None = "0e411c078c0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_api_cost_log_call_date"), "api_cost_log", ["call_date"], unique=False)
    op.create_index(
        "ix_daily_digest_date_current", "daily_digest", ["digest_date", "is_current"], unique=False
    )
    op.create_index(
        op.f("ix_daily_digest_digest_date"), "daily_digest", ["digest_date"], unique=False
    )
    op.create_index(op.f("ix_digest_items_digest_id"), "digest_items", ["digest_id"], unique=False)
    op.create_index(
        "ix_job_run_type_date_status",
        "job_runs",
        ["job_type", "digest_date", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_topics_digest_date"), "topics", ["digest_date"], unique=False)
    op.create_index(op.f("ix_tweets_account_id"), "tweets", ["account_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tweets_account_id"), table_name="tweets")
    op.drop_index(op.f("ix_topics_digest_date"), table_name="topics")
    op.drop_index("ix_job_run_type_date_status", table_name="job_runs")
    op.drop_index(op.f("ix_digest_items_digest_id"), table_name="digest_items")
    op.drop_index(op.f("ix_daily_digest_digest_date"), table_name="daily_digest")
    op.drop_index("ix_daily_digest_date_current", table_name="daily_digest")
    op.drop_index(op.f("ix_api_cost_log_call_date"), table_name="api_cost_log")
    # ### end Alembic commands ###
